# Build Spec for AWS CodeBuild CI - SMOKE

version: 0.2

phases:
  build:
    commands:
      # create and install build
      - ci/scripts/linux_build.sh
      - pip install dist/*
      # modelarchiver tests
      - ci/scripts/linux_test_modelarchiver.sh
      # run python tests
      - ci/scripts/linux_test_python.sh

artifacts:
  files:
    - '**/*'
  name: build_artifacts
  base-directory: frontend/server/build/reports/tests/test
  secondary-artifacts:
    model-archiver-tests:
      files:
        - '**/*'
      name: model_archiver_tests
      base-directory: model-archiver/results_units
    mms_tests:
      files:
        - '**/*'
      name: mms_python_units
      base-directory: results_units/