# Build Spec for AWS CodeBuild CI - Nightly

version: 0.2

phases:
  build:
    commands:
      # create and install build
      - ci/scripts/linux_build.sh
      - pip install dist/*
      # modelarchiver tests
      - ci/scripts/linux_test_modelarchiver.sh
      # run python tests
      - ci/scripts/linux_test_python.sh
      # run api tests
#      - ci/scripts/linux_test_api.sh management
#      - ci/scripts/linux_test_api.sh inference
#      - ci/scripts/linux_test_api.sh https

artifacts:
  secondary-artifacts:
    build_artifacts:
      files:
        - '**/*'
      name: MMS-NIGHTLY-$(date +%Y-%m-%d)/build_artifacts
      base-directory: frontend/server/build/reports/tests/test
    model_archiver_tests:
      files:
        - '**/*'
      name: MMS-NIGHTLY-$(date +%Y-%m-%d)/model_archiver_tests
      base-directory: model-archiver/result_units
    mms_tests:
      files:
        - '**/*'
      name: MMS-NIGHTLY-$(date +%Y-%m-%d)/mms_python_units
      base-directory: result_units/